### ISSUE TITLE
Source code button for each project should let you pick the platform

### ISSUE THREAD

**Issue by avipars** [CodeDead/codedead.com#23]
![image](https://github.com/CodeDead/codedead.com/assets/5733247/5cad3fb1-e5a2-4691-9443-4658fc2c862c)

For example, with DeadHash, if I want to see the android source code... currently, I would need to go to your github repos and search to find it as the link only brings me to the JS (react) version...

Maybe have a dropdown with the platform relevant or split it into separate buttons for each platform

**Comment by CodeDead** [comment]
This is quick fix. Consider it done soon™️. Thanks for the suggestion!
